#!/bin/bash
exec 2>/dev/null
#
# Check the working folder write permission
#
DIR=$PWD
INFO=( $(stat -c "%a %U" $DIR) )
PERM=${INFO[0]}
OWNER=${INFO[1]}
case $PERM in
755)
        echo ""
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        echo ""
        echo " You have no permission to write this folder."
        echo " Invite the $OWNER to grant permission to this directory."
        echo ""
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        exit 1
        ;;
esac
#
# This number is used by the grep command.
#
# From: 
# Manual page grep(1)
# -A NUM, --after-context=NUM
#        Print  NUM  lines of trailing context after matching lines.
#
A=50
#
# Read and write HTML file names to the array
# 
readarray farray <<< "$(ls -f *.HTML)"
# 
#ls -f *.HTML  > tmp.txt
#
#readarray farray < tmp.txt
#
# If there is no HTML file in the directory then exit with status 1
#
if [ -z $farray ]
   then
   echo ""
   echo "
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                  There is no HTML file in this folder !!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
#   rm -r tmp.txt
   exit 1
fi
#
#rm tmp.txt
#
# The cycle runs as many HTML files are in the directory
#
echo "--------------------------------------------------------------------------------"
echo "  Program név                           |         Programfuttatások száma       "
e=0
while [ "z${farray[e]}" != "z" ]
do
#
   db=( $(cat ${farray[e]} | grep -a "PROGRAMFUTTAT" -A1 | tail -n1 | cut -d "&" -f1 | cut -d ">" -f3) )

#   readarray parray < piece_tmp.txt # Read and write piece to array

#   rm piece_tmp.txt

#   pdb=`echo ${barray[*]} | wc -w`

   pname=( $(echo ${farray[e]} | cut -d "." -f1) )

#
   echo "--------------------------------------------------------------------------------"
   echo " $pname						$db db"
#
   e=$(( $e + 1 ))
done
echo "--------------------------------------------------------------------------------"
exit 0
